### ISSUE TITLE
where is the hypertuning.py file?

### ISSUE THREAD

**Issue by walkacross** [maohangyu/TIT_open_source#1]
hi @maohangyu, 

thanks for this paper and its open source code.

I wonder where is the hypertuning.py file? cause the run.sh need to use it to hyper tuning to replicate the results

**Comment by maohangyu** [comment]
> 



> hi @maohangyu,
> 
> thanks for this paper and its open source code.
> 
> I wonder where is the hypertuning.py file? cause the run.sh need to use it to hyper tuning to replicate the results

1. Our hypertuning.py file is highly based on the following code:
https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/rl_zoo3/exp_manager.py#L816

2. You should write your hypertuning methods for different environemnts.

**Comment by walkacross** [comment]
got it. 

thanks for your response, have a good day
